### ISSUE TITLE
Fix: README, Invalid link to key-value vs value store document

### ISSUE THREAD

**Issue by cadesalaberry** [infinit/memo#2]
The [ XXX: When shoould I use the value store against the key-value store.](https://github.com/infinit/memo/blob/master) link in the README leads nowhere.

> The key-value store uses the value store to provide a higher-level interface like common key-value stores (etcd, ZooKeeper, etc.), where arbitrary data can be stored under an arbitrary name.
>
> The value store is the lowest brick of the architecture, providing the fundamental object named blocks, declined in a few flavors. Those blocks are cryptographically protected, their addresses are chosen randomly to guarantee a homogeneous distribution and prevent XXX(squating) and all operations are atomic, but the caller is responsible for keeping addresses.
>
> For more details you can consult [ XXX: When shoould I use the value store against the key-value store.](https://github.com/infinit/memo/blob/master)

**Comment by Dimrok** [comment]
Yes, the XXX stands for "it's a placeholder until we have a specific page on the website". 

I pretty sure we have one now so I'll remove the XXX and fix the link.

Thanks.

**Comment by Dimrok** [comment]
Fixed. 

Thank you.
